---
title: "estado de las especies"
output: html_document
date: "2022-09-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
library(dplyr)

```


```{r}
estatus_spp <- read_excel("C:/github/pat/prep/SPP/spp3.0.xlsx")
estatus_spp1<- filter(estatus, year >=2000)
```

```{r}
## Primer factor 
status <- estatus_spp1 %>%
  dplyr::group_by(rgn_id, id) %>%
  dplyr::summarize(suma = sum(category), n_sp =n()) 


h<- estatus_spp1 %>% select(rgn_id, id,  area_km2) 
h<-h[!duplicated(h), ]

status<- merge(status, h)

status <- status %>%
  dplyr::mutate(A = (1 - (suma/n_sp))) %>%
  dplyr::mutate(B = A * area_km2) %>%
  dplyr::group_by(rgn_id) %>%
  dplyr::summarize(A = sum(B))

##Segundo factor
h<- estatus_spp1 %>% select(rgn_id, area_km2, id, area_km2) 
h<-h[!duplicated(h), ]

status2 <- h %>%
  dplyr::group_by(rgn_id) %>%
  dplyr::summarize(area_rgn = sum(area_km2)) 

status<- merge(status, status2, all.y = FALSE)

##Calculo del estado actual 
status_spp <- status %>%
  dplyr::mutate(score= (A / area_rgn)*100)    %>% 
     dplyr::mutate(
       dimension = 'status') %>% 
  dplyr::select(region_id = "rgn_id", score, dimension)

```








status_spp<- scores_spp %>%
